[theme]
# Primary colors
primaryColor = "#FF6B6B"          # Red accent color for interactive elements
backgroundColor = "#EEFFCC"       # White background
secondaryBackgroundColor = "#F0F2F6"  # Light gray for sidebar and containers

# Text colors
textColor = "#262730"             # Dark gray for main text

# Fonts
font = "sans serif"               # Clean, modern font
